name: Build, Branch, and Release React Vite App

on:
  push:
    branches:
      - main

permissions:
  contents: write
  actions: read

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Create zip archive
        run: |
          cd dist
          zip -r ../build-${{ github.sha }}.zip .

      - name: Get commit info
        id: commit
        run: |
          echo "message=$(git log -1 --pretty=%B)" >> $GITHUB_OUTPUT
          echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: build-${{ steps.commit.outputs.short_sha }}
          name: Build ${{ steps.commit.outputs.short_sha }}
          body: |
            🚀 **Automated Build Release**

            **Commit:** ${{ github.sha }}
            **Message:** ${{ steps.commit.outputs.message }}
            **Built from:** `main` branch
            **Build Date:** ${{ github.event.head_commit.timestamp }}

            This release contains the built locally deployable extension for chromium based browsers.
          files: build-${{ github.sha }}.zip
          draft: false
          prerelease: false
